stages:
  - build_images
  - run_tests

.build_template: &build_template
  image:
    name: docker
  script:
  - docker buildx build -t "$image" - < "$dockerfile"
  stage: build_images
  tags:
  - docker

normal:
  <<: *build_template
  variables:
    dockerfile: ${CI_PROJECT_DIR}/ci/Dockerfile
    image: ${CI_REGISTRY_IMAGE}:normal

portable:
  <<: *build_template
  variables:
    dockerfile: ${CI_PROJECT_DIR}/ci/Dockerfile.portable
    image: ${CI_REGISTRY_IMAGE}:portable

.template: &template
  image:
    name: ${image}
  before_script:
  - git config --global http.sslCAInfo "${CI_SERVER_TLS_CA_FILE}"
  - git clone "${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_NAMESPACE}/iris.git" iris_src
  - cd iris_src
  - git clean -ffdx
  - git fetch origin
  - git checkout b616981626b5a4f9df904131ef00f637d3dd984f
  - git log -1
  - cmake -S "${CI_PROJECT_DIR}/iris_src" -B "${CI_PROJECT_DIR}/iris_build" "-DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/iris"
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=YES -DTRACE_DISABLE=YES -DDEBUG_DISABLE=YES
  - cmake --build "${CI_PROJECT_DIR}/iris_build" -j 4
  - cmake --install "${CI_PROJECT_DIR}/iris_build"
  script:
  - ${CI_PROJECT_DIR}/ci/test.sh
  stage: run_tests
  tags:
  - docker
  - cuda

normal_debug:
  <<: *template
  variables:
    CHARM_SYCL_CUDA_IS_REQUIRED: "YES"
    CHARM_SYCL_HIP_IS_REQUIRED: "YES"
    CMAKE_BUILD_TYPE: Debug
    CSCC_PORTABLE_MODE: "NO"
    GIT_SUBMODULE_STRATEGY: normal
    image: ${CI_REGISTRY_IMAGE}:normal
    IRIS_DIR: ${CI_PROJECT_DIR}/iris

normal_release:
  <<: *template
  variables:
    CHARM_SYCL_CUDA_IS_REQUIRED: "YES"
    CHARM_SYCL_HIP_IS_REQUIRED: "YES"
    CMAKE_BUILD_TYPE: Release
    CSCC_PORTABLE_MODE: "NO"
    GIT_SUBMODULE_STRATEGY: normal
    image: ${CI_REGISTRY_IMAGE}:normal
    IRIS_DIR: ${CI_PROJECT_DIR}/iris

portable_debug:
  <<: *template
  variables:
    CHARM_SYCL_CUDA_IS_REQUIRED: "NO"
    CHARM_SYCL_HIP_IS_REQUIRED: "NO"
    CMAKE_BUILD_TYPE: Debug
    CSCC_PORTABLE_MODE: "YES"
    GIT_SUBMODULE_STRATEGY: normal
    image: ${CI_REGISTRY_IMAGE}:portable
    IRIS_DIR: ${CI_PROJECT_DIR}/iris
  artifacts:
    name: "debug-${CI_COMMIT_SHA}"
    paths:
    - build/src/cscc/cscc

portable_release:
  <<: *template
  variables:
    CHARM_SYCL_CUDA_IS_REQUIRED: "NO"
    CHARM_SYCL_HIP_IS_REQUIRED: "NO"
    CMAKE_BUILD_TYPE: Release
    CSCC_PORTABLE_MODE: "YES"
    GIT_SUBMODULE_STRATEGY: normal
    image: ${CI_REGISTRY_IMAGE}:portable
    IRIS_DIR: ${CI_PROJECT_DIR}/iris
  artifacts:
    name: "release-${CI_COMMIT_SHA}"
    paths:
    - build/src/cscc/cscc
