[workspace]
resolver = "2"
members = [
    "crates/cuda-ifgen",
    "crates/id-range-gen",
    "crates/ifgen",
]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
sailfish = "0.8"
itertools = "0.12.1"
ifgen = { path = "crates/ifgen" }
